trustPolicy: no-downgrade
ignoreScripts: true
strictDepBuilds: true
minimumReleaseAge: 2880 # 48hs
blockExoticSubdeps: true

allowBuilds:
  lefthook: true

trustPolicyExclude:
  - semver@5.7.2
  - semver@6.3.1
